[2023-08-27T01:52:49.965+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: analytics_pipeline_dag.run_pipeline_task scheduled__2023-08-20T01:47:12.062789+00:00 [queued]>
[2023-08-27T01:52:49.969+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: analytics_pipeline_dag.run_pipeline_task scheduled__2023-08-20T01:47:12.062789+00:00 [queued]>
[2023-08-27T01:52:49.969+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-08-27T01:52:49.977+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_pipeline_task> on 2023-08-20 01:47:12.062789+00:00
[2023-08-27T01:52:49.987+0000] {standard_task_runner.py:57} INFO - Started process 327 to run task
[2023-08-27T01:52:49.990+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'analytics_pipeline_dag', 'run_pipeline_task', 'scheduled__2023-08-20T01:47:12.062789+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/my_proyects/my_first_dag.py', '--cfg-path', '/tmp/tmpbhoroj8k']
[2023-08-27T01:52:49.991+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask run_pipeline_task
[2023-08-27T01:52:50.023+0000] {task_command.py:415} INFO - Running <TaskInstance: analytics_pipeline_dag.run_pipeline_task scheduled__2023-08-20T01:47:12.062789+00:00 [running]> on host 213cf445b0df
[2023-08-27T01:52:50.068+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='analytics_pipeline_dag' AIRFLOW_CTX_TASK_ID='run_pipeline_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-20T01:47:12.062789+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-20T01:47:12.062789+00:00'
[2023-08-27T01:52:50.938+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_proyects/my_first_dag.py", line 51, in run_analytics_pipeline
    week_start_date_strings = extractor_loader.get_week_start_dates(dimensions, metrics, order_bys, date_range)
AttributeError: 'AnalyticsExtractorAndLoader' object has no attribute 'get_week_start_dates'
[2023-08-27T01:52:50.947+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=analytics_pipeline_dag, task_id=run_pipeline_task, execution_date=20230820T014712, start_date=20230827T015249, end_date=20230827T015250
[2023-08-27T01:52:50.958+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 53 for task run_pipeline_task ('AnalyticsExtractorAndLoader' object has no attribute 'get_week_start_dates'; 327)
[2023-08-27T01:52:51.003+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-27T01:52:51.017+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
